source 'https://rubygems.org'

gem 'actionpack'
gem 'activesupport'
gem 'activerecord', :require => 'active_record'

gem 'colorize'
gem 'pry'
gem 'awesome_print'

#{Cear::File.add_gems(CearConfig.include_pg, ['pg', 'postgres_ext', 'standalone_migrations'])}
#{Cear::File.add_gems(CearConfig.include_redis, ['redis'])}
